### ISSUE TITLE
Error on opening loot window with 3.0.4

### ISSUE THREAD

**Issue by Voidheartd** [nmsmith22389/HotLoot#11]
Error occurs when looting, no items get looted, only gold. Reverting to 3.0.3 fixed issue.

Date: 2016-11-03 06:12:07
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\HotLoot\HotLoot.lua line 995:
   attempt to concatenate local 'itemID' (a nil value)
Debug:
   HotLoot\HotLoot.lua:995:
      HotLoot\HotLoot.lua:966
   HotLoot\HotLoot.lua:1793: ?()
   ...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147:
      ...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119

**Comment by Spydawg** [comment]
same issue.  I'll try going back to 3.0.3

**Comment by Spydawg** [comment]
Yes 3.0.3 works for me as well

**Comment by nmsmith22389** [comment]
Thanks for bringing this up! It was a problem with a debug string that was pulling from a broken function. I just released a hotfix (v3.0.5) that should fix the problem. Thanks! Let me know if you have any more problems with it.

**Comment by nmsmith22389** [comment]
Looks like theres more problems than I thought. Look out for v3.0.6!

**Comment by nmsmith22389** [comment]
For me Tradeskill items that used to come up as "item type = Tradeskill" like cloth and leather are now coming up as "item type = Item Enhancement!" _(including that exclamation mark!)_ Is it just me or is it like that for everyone?

to check type `/script print(GetItemInfo(2318))` into chat and see if it says "Tradeskill" or "Item Enhancement"

**Comment by Spydawg** [comment]
Light Leather [Light Leather] 1 10 0 Item Enhancement! Leather 200  134252 15 7 6 0 0 nil true

**Comment by nmsmith22389** [comment]
That's so weird! What the hell is "Item Enhancement!"! It was always Tradeskill! Maybe a bug or something? I should post on the forums or something and see. It messed up all of the profession filters.

**Comment by nmsmith22389** [comment]
Either way, I released v3.0.6 which should fix that problem along with the others such as the skinning mode not working. Let me know if you have more problems! Thanks!

**Comment by nmsmith22389** [comment]
**UPDATE:** I posted a topic on the WoW forums so we will see what they say.
