### ISSUE TITLE
Error when attempting to add item to exclude

### ISSUE THREAD

**Issue by Voidheartd** [nmsmith22389/HotLoot#13]
Trying to add gem chips to the exclusions, fails with this error:

Date: 2016-11-06 05:32:56
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\HotLoot\HotLoot.lua line 1296:
   attempt to call method 'AddEList' (a nil value)
Debug:
   HotLoot\HotLoot.lua:1296:
      HotLoot\HotLoot.lua:1295
   HotLoot\HotLoot.lua:1669:
      HotLoot\HotLoot.lua:1669
Locals:
name = "[Gem Chip]"
(*temporary) = nil
(*temporary) = <table> {
 GetSkinningModeModifier = <function> defined @Interface\AddOns\HotLoot\Options.lua:1842
 SetLootGridNumColumns = <function> defined @Interface\AddOns\HotLoot\Options.lua:1651
 modules = <table> {
 }
 addLootIcon = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:1326
 GetShowLootMonitorAnchor = <function> defined @Interface\AddOns\HotLoot\Options.lua:1447
 LoadTheme = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:218
 SetColorByQuality = <function> defined @Interface\AddOns\HotLoot\Options.lua:1552
 MakeColor = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:265
 SetSkinningModeModifier = <function> defined @Interface\AddOns\HotLoot\Options.lua:1838
 GetLootGridNumColumns = <function> defined @Interface\AddOns\HotLoot\Options.lua:1655
 SetSystemEnable = <function> defined @Interface\AddOns\HotLoot\Options.lua:1424
 SetShowLootMonitorAnchor = <function> defined @Interface\AddOns\HotLoot\Options.lua:1442
 GetExcludeList = <function> defined @Interface\AddOns\HotLoot\Options.lua:2289
 SetTextSide = <function> defined @Interface\AddOns\HotLoot\Options.lua:1524
 SetLootGridMode = <function> defined @Interface\AddOns\HotLoot\Options.lua:1629
 SetShowTotalQuant = <function> defined @Interface\AddOns\HotLoot\Options.lua:1488
 SetQuestFilter = <function> defined @Interface\AddOns\HotLoot\Options.lua:1697
 GetShowTotalQuant = <function> defined @Interface\AddOns\HotLoot\Options.lua:1492
 db = <table> {
 }
 GetTrackerEnable = <function> defined @Interface\AddOns\HotLoot\Options.lua:2391
 GetUnitLoot = <function> defined @Interface\AddOns\HotLoot\Options.lua:1763
 GetQuestFilter = <function> defined @Interface\AddOns\HotLoot\Options.lua:1701
 GetTextSide = <function> defined @Interface\AddOns\HotLoot\Options.lua:1528
 GetUnitClose = <function> defined @Interface\AddOns\HotLoot\Options.lua:1771
 SetArtifactQualityFilter = <function> defined @Interface\AddOns\HotLoot\Options.lua:2186
 NewModule = <function> defined @Interface\AddOns\Archy\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 GetPickpocketFilter = <function> defined @Interface\AddOns\HotLoot\Options.lua:1719
 GetPoorQualityFilter = <function> defined @Interface\AddOns\HotLoot\Options.lua:2127
 CONFIRM_LOOT_ROLL = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:1895
 GetName = <function> defined @Interface\AddOns\Archy\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "HotLoot"
 LOOT_SLOT_CLEARED = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:1851
 Disable = <function> defined @Interface\AddOns\Archy\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 SetFadeSpeed = <function> defined @Interface\AddOns\HotLoot\Options.lua:1611
 GetAdvancedOptions = <function> defined @Interface\AddOns\HotLoot\Options.lua:1812
 GetColorByQuality = <function> defined @Interface\AddOns\HotLoot\Options.lua:1556
 GetAdvancedOptionsHidden = <function> defined @Interface\AddOns\HotLoot\Options.lua:1815
 RemoveFromExcludeList = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:567
 GetFadeSpeed = <function> defined @Interface\AddOns\HotLoot\Options.lua:1615
 Debug = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:475
 SetPickpocketFilter = <function> defined @Interface\AddOns\HotLoot\Options.lua:1715
 ChatCommand = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:438
 GetTrackerGoal = <function> defined @Interface\AddOns\HotLoot\Options.lua:2416
 SetAdvancedOptions = <function> defined @Interface\AddOns\HotLoot\Options.lua:1808
 GetShowExcludeButton = <function> defined @Interface\AddOns\HotLoot\Options.lua:2298
 ToggleKeywordHide = <function> defined @Interface\AddOns\HotLoot\Options.lua:1749
 buttonTestLootMonitor = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:501
 RemoveFromIncludeList = <function> defined @Interface\AddOns\HotLoot\HotLoot.lua:552
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Archy\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 GetPotionFilter = <function> defined @Interface\AddOns\HotLoot\Opt

**Comment by nmsmith22389** [comment]
It looks like the exclude function was not named right and so it caused the error. I've since fixed it in v3.0.7. It does look like v3.0.7 is taking a minute to update to curse so if it's not there by the time you look for it, you can always get it from [the GitHub release](https://github.com/nmsmith22389/HotLoot/releases/tag/v3.0.7).

Thanks!
