### ISSUE TITLE
Exclude List

### ISSUE THREAD

**Issue by MrCr0w-legacy** [nmsmith22389/HotLoot#14]
When I add an item [(Steel Lockbox)](http://www.wowhead.com/item=4637/steel-lockbox#english-comments) on the exclusion list, this happens:

Date: 2016-11-07 11:12:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\HotLoot\Options.lua line 2271:
   attempt to call method 'AddEList' (a nil value)
Debug:
   HotLoot\Options.lua:2271:
      HotLoot\Options.lua:2268
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[3]"]:9:
      [string "safecall Dispatcher[3]"]:5
   (tail call): ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:794:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[3]"]:9:
      [string "safecall Dispatcher[3]"]:5
   (tail call): ?
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
   ...er4\libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:74:
      ...er4\libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:71
   ...er4\libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:120:
      ...er4\libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:117
Locals:
None
AddOns:
  Swatter, v7.2.5688 (TasmanianThylacine)
  NPCScanOverlay, v7.1.0.1
  ACP, v3.4.30 
  AdiBags, vv1.9.4
  APeonsBurden, vv2.4
  AucAdvanced, v7.2.5688 (TasmanianThylacine)
  AucFilterBasic, v7.2.5688 (TasmanianThylacine)
  AucFilterOutlier, v7.2.5688.5459(7.2/embedded)
  AucMatchUndercut, v7.2.5688.5585(7.2/embedded)
  AucScanData, v7.2.5688 (TasmanianThylacine)
  AucStatHistogram, v7.2.5688 (TasmanianThylacine)
  AucStatiLevel, v7.2.5688 (TasmanianThylacine)
  AucStatPurchased, v7.2.5688 (TasmanianThylacine)
  AucStatSales, v7.2.5688.5598(7.2/embedded)
  AucStatSimple, v7.2.5688 (TasmanianThylacine)
  AucStatStdDev, v7.2.5688 (TasmanianThylacine)
  AucStatWOWEcon, v7.2.5688.5613(7.2/embedded)
  AucUtilAHWindowControl, v7.2.5688.5575(7.2/embedded)
  AucUtilAppraiser, v7.2.5688.5666(7.2/embedded)
  AucUtilAskPrice, v7.2.5688.5599(7.2/embedded)
  AucUtilAutoMagic, v7.2.5688.5686(7.2/embedded)
  AucUtilCompactUI, v7.2.5688.5629(7.2/embedded)
  AucUtilEasyBuyout, v7.2.5688.5576(7.2/embedded)
  AucUtilFixAH, v7.2.5688 (TasmanianThylacine)
  AucUtilItemSuggest, v7.2.5688.5651(7.2/embedded)
  AucUtilPriceLevel, v7.2.5688.5633(7.2/embedded)
  AucUtilScanButton, v7.2.5688.5631(7.2/embedded)
  AucUtilScanFinish, v7.2.5688.5588(7.2/embedded)
  AucUtilScanProgress, v7.2.5688.4979(7.2/embedded)
  AucUtilScanStart, v7.2.5688.5347(7.2/embedded)
  AucUtilSearchUI, v7.2.5688.5672(7.2/embedded)
  AucUtilSimpleAuction, v7.2.5688.5654(7.2/embedded)
  AucUtilVendMarkup, v7.2.5688.4828(7.2/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.1.13
  Bartender4, v4.7.4
  BeanCounter, v7.2.5688 (TasmanianThylacine)
  Configator, v5.1.DEV.406(/embedded)
  ConfirmSP, v01-38
  DebugLib, v5.1.DEV.337(/embedded)
  DropTheCheapestThing, vv70000.2
  DugisGuideViewerZ, v4.043
  Enchantrix, v7.2.5688 (TasmanianThylacine)
  EnchantrixBarker, v7.2.5688 (TasmanianThylacine)
  ExplorerCoords, v1.6
  FlightMap, v7.0.0.6
  HealersHaveToDie, v2.4.3
  HotLoot, v3.0.6
  IceHUD, v1.10.11
  iLvLr, v2.3.302
  Informant, v7.2.5688 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.416(/embedded)
  LibQTip10, vr178-release 
  Mappy, v3.7
  MobKillCount, v7.1.0
  MoveAnything, v16.1.1
  NPCScan, v7.1.0.1
  Overachiever, v0.98
  Prat30, v3.6.19      
  Prat30Libraries, v
  QuestCompletist, v107
  Questomatic, v2.6
  Scrap, v13.3
  ScrapSpotlight, v13.3
  SellOMatic2, va068
  SellOMatic2Destroy, va068
  SellOMatic2Item, va068
  SellOMatic2List, va068
  Skillet, v3.14
  SlideBar, v7.2.5688 (TasmanianThylacine)
  Stubby, v7.2.5688 (TasmanianThylacine)
  Tip, v1.10
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.10.27
  TipTacItemRef, v16.10.27
  TipTacTalents, v16.10.27
  Titan, v5.9.3.70100
  TitanBag, v5.9.3.70100
  TitanClock, v5.9.3.70100
  TitanGold, v5.9.3.70100
  TitanLocation, v5.9.3.70100
  TitanLootType, v5.9.3.70100
  TitanPerformance, v5.9.3.70100
  TitanRepair, v5.9.3.70100
  TitanVolume, v5.9.3.70100
  TitanXP, v5.9.3.70100
  TomTom, vv70000-1.1.0
  TradeLog, v
  WorldQuestsList, v23
  WorldQuestTracker, v
  WowheadLinkGrabber, vv1.1
  XLoot, v7.1-1
  XLootFrame, v7.1-1
  XLootGroup, v7.1-1
  XLootMaster, v7.1-1
  XLootMonitor, v7.1-1
  BlizRuntimeLib_ptBR v7.1.0.70100 <none>
  (ck=c84)

**Comment by nmsmith22389** [comment]
This problem was identified in issue #13 and solved in v3.0.7 however, it was delayed when it wouldn't properly upload to curse. It is now uploaded and working properly. Thanks!
