### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rmcgraw1** [nmsmith22389/HotLoot#15]
Only Thing id like added is the ability to make the fonts bigger either with a slider or just more themes with bigger fonts

**Comment by nmsmith22389** [comment]
Sorry it took me so long to get back to you!

I actually have this 90% implemented I just have had so many projects going that I haven't had the time to finish it. I promise you that the second I get the chance I'll update it. Thanks!

**Comment by nmsmith22389** [comment]
Sorry it took so long! Font stuff should be included in the next update which is any day now. I know that font and color are in there but ill have to double check to see if size is too. Thanks!

**Comment by nmsmith22389** [comment]
This should all be added now in the latest available version! thanks!
