### ISSUE TITLE
Compiling Language & Update 7.1.5

### ISSUE THREAD

**Issue by MrCr0w-legacy** [nmsmith22389/HotLoot#16]
Hello friend, I don't understand a lot of programming LUA files, but I have using the Localization tool available by curseforge.com, so I did the translation for my language and I would like to know how I can do to "compile".

P.S: Sorry, I'm talking about HotLoot (One of the best addons for me)

**Comment by nmsmith22389** [comment]
Hi sorry it took me so long to get to you! I have to actually include it into the addon. I'll be doing an update for 7.2 in the next day or two so I can include it in. Could you please tell me which language so I can make sure it's added?

Thanks for helping out!

**Comment by nmsmith22389** [comment]
This should be included in the latest available version. Thanks!
