### ISSUE TITLE
Added newer item qualities to filter!

### ISSUE THREAD

**Issue by nmsmith22389** [nmsmith22389/HotLoot#2]
Add Artifact (6) and Heirloom (7) to the loot filter.
_(They weren't around when the addon was first written.)_

_For the loot qualities see [here](http://wow.gamepedia.com/API_TYPE_Quality)_

**Comment by dsblack115** [comment]
This should be Artifact (6).

**Comment by nmsmith22389** [comment]
@dsblack115 Thanks! I fixed it! I also added it to the addon but without an Artifact or Heirloom to loot I can't really test it... I'm reasonably sure it will work though.

**Comment by dsblack115** [comment]
Ok since Legion started I know what Artifact weapons are, but Heirlooms I have no clue.  I was told you get these when maxing out a character, but I've maxed out a character and don't have Heirlooms.  There must be a whole lot of end game content I have yet to experience.

**Comment by nmsmith22389** [comment]
Yeah heirlooms are items you get around end game but they aren't for your high lvl char. They are meant to be given to your lower lvl chars to help lvl them up. They scale based on lvl.

**Comment by dsblack115** [comment]
I gotta read up on how to do this so when I max out one or two during this exp I can get heirlooms for lower level characters.  I'm such a WoW noob, and I've been playing on and off for 6-7 years.
