### ISSUE TITLE
Stonehide Leather

### ISSUE THREAD

**Issue by dsblack115** [nmsmith22389/HotLoot#8]
HL deletes upon loot.  Loots fine after added to the included list.

**Comment by dsblack115** [comment]
HL deletes **Stormscale** upon loot.  Added to included list.

**Comment by nmsmith22389** [comment]
Both this issue and #7 are the same as #4 and are fixed in v3.0.4 which will be released very shortly. The fix should solve _all_ skinning mode problems. Thanks and stay tuned!
